version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
      - 443:443

  irmin:
    build:
      context: .
      dockerfile: Dockerfile.irmin
    volumes:
      - irmin_fs:/tmp/irmin:rw

  svelte:
    build:
      context: .
      dockerfile: Dockerfile.svelte
    volumes:
      - ./front-end/src:/home/docker/front-end/src

volumes:
  irmin_fs:
